[project]
name = "canela"
version = "0.2.0"
description = "Private Security System for the Homestead"
authors = [{ name = "mariofix", email = "yo@mariofix.com" }]
readme = "README.md"
requires-python = ">=3.10,<3.15"
dependencies = [
    "opencv-python (>=5.0.0.93,<6.0.0.0)",
    "python-dotenv (>=1.2.3,<2.0.0)",
    "requests (>=2.34.2,<3.0.0)",
    "dynaconf (>=3.2.0,<4.0.0)",
    "numpy (>=1.26,<3.0)",
    "blinker (>=1.7,<2.0)",
]

[tool.poetry]
packages = [{ include = "canela", from = "src" }]

[project.scripts]
motion = "canela.cli:main"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
